/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetContactCampaignStatsClicked } from './getContactCampaignStatsClicked';
import { GetContactCampaignStatsOpened } from './getContactCampaignStatsOpened';
import { GetContactCampaignStatsTransacAttributes } from './getContactCampaignStatsTransacAttributes';
import { GetContactCampaignStatsUnsubscriptions } from './getContactCampaignStatsUnsubscriptions';
import { GetExtendedContactDetailsAllOfStatisticsMessagesSent } from './getExtendedContactDetailsAllOfStatisticsMessagesSent';

/**
* Campaign Statistics for the contact
*/
export class GetContactCampaignStats {
    'messagesSent'?: Array<GetExtendedContactDetailsAllOfStatisticsMessagesSent>;
    'hardBounces'?: Array<GetExtendedContactDetailsAllOfStatisticsMessagesSent>;
    'softBounces'?: Array<GetExtendedContactDetailsAllOfStatisticsMessagesSent>;
    'complaints'?: Array<GetExtendedContactDetailsAllOfStatisticsMessagesSent>;
    'unsubscriptions'?: GetContactCampaignStatsUnsubscriptions;
    'opened'?: Array<GetContactCampaignStatsOpened>;
    'clicked'?: Array<GetContactCampaignStatsClicked>;
    'transacAttributes'?: Array<GetContactCampaignStatsTransacAttributes>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "messagesSent",
            "baseName": "messagesSent",
            "type": "Array<GetExtendedContactDetailsAllOfStatisticsMessagesSent>"
        },
        {
            "name": "hardBounces",
            "baseName": "hardBounces",
            "type": "Array<GetExtendedContactDetailsAllOfStatisticsMessagesSent>"
        },
        {
            "name": "softBounces",
            "baseName": "softBounces",
            "type": "Array<GetExtendedContactDetailsAllOfStatisticsMessagesSent>"
        },
        {
            "name": "complaints",
            "baseName": "complaints",
            "type": "Array<GetExtendedContactDetailsAllOfStatisticsMessagesSent>"
        },
        {
            "name": "unsubscriptions",
            "baseName": "unsubscriptions",
            "type": "GetContactCampaignStatsUnsubscriptions"
        },
        {
            "name": "opened",
            "baseName": "opened",
            "type": "Array<GetContactCampaignStatsOpened>"
        },
        {
            "name": "clicked",
            "baseName": "clicked",
            "type": "Array<GetContactCampaignStatsClicked>"
        },
        {
            "name": "transacAttributes",
            "baseName": "transacAttributes",
            "type": "Array<GetContactCampaignStatsTransacAttributes>"
        }    ];

    static getAttributeTypeMap() {
        return GetContactCampaignStats.attributeTypeMap;
    }
}

