export * from './abTestCampaignResult';
export * from './abTestCampaignResultClickedLinks';
export * from './abTestCampaignResultStatistics';
export * from './abTestVersionStats';
export * from './addChildDomain';
export * from './addContactToList';
export * from './addCredits';
export * from './blockDomain';
export * from './createAttribute';
export * from './createAttributeEnumeration';
export * from './createChild';
export * from './createContact';
export * from './createDoiContact';
export * from './createEmailCampaign';
export * from './createEmailCampaignRecipients';
export * from './createEmailCampaignSender';
export * from './createList';
export * from './createModel';
export * from './createReseller';
export * from './createSender';
export * from './createSenderIps';
export * from './createSenderModel';
export * from './createSmsCampaign';
export * from './createSmsCampaignRecipients';
export * from './createSmtpEmail';
export * from './createSmtpTemplate';
export * from './createSmtpTemplateSender';
export * from './createUpdateContactModel';
export * from './createUpdateFolder';
export * from './createWebhook';
export * from './createdProcessId';
export * from './deleteHardbounces';
export * from './emailExportRecipients';
export * from './errorModel';
export * from './getAccount';
export * from './getAccountAllOf';
export * from './getAccountAllOfMarketingAutomation';
export * from './getAccountAllOfPlan';
export * from './getAccountAllOfRelay';
export * from './getAccountAllOfRelayData';
export * from './getAggregatedReport';
export * from './getAttributes';
export * from './getAttributesAttributes';
export * from './getAttributesEnumeration';
export * from './getBlockedDomains';
export * from './getCampaignOverview';
export * from './getCampaignRecipients';
export * from './getCampaignStats';
export * from './getChildAccountCreationStatus';
export * from './getChildDomain';
export * from './getChildInfo';
export * from './getChildInfoAllOf';
export * from './getChildInfoAllOfApiKeys';
export * from './getChildInfoAllOfApiKeysV2';
export * from './getChildInfoAllOfApiKeysV3';
export * from './getChildInfoAllOfCredits';
export * from './getChildInfoAllOfStatistics';
export * from './getChildrenList';
export * from './getClient';
export * from './getContactCampaignStats';
export * from './getContactCampaignStatsClicked';
export * from './getContactCampaignStatsOpened';
export * from './getContactCampaignStatsTransacAttributes';
export * from './getContactCampaignStatsUnsubscriptions';
export * from './getContactDetails';
export * from './getContacts';
export * from './getDeviceBrowserStats';
export * from './getEmailCampaign';
export * from './getEmailCampaignAllOf';
export * from './getEmailCampaigns';
export * from './getEmailEventReport';
export * from './getEmailEventReportEvents';
export * from './getExtendedCampaignOverview';
export * from './getExtendedCampaignOverviewAllOf';
export * from './getExtendedCampaignOverviewAllOfSender';
export * from './getExtendedCampaignStats';
export * from './getExtendedClient';
export * from './getExtendedClientAllOf';
export * from './getExtendedClientAllOfAddress';
export * from './getExtendedContactDetails';
export * from './getExtendedContactDetailsAllOf';
export * from './getExtendedContactDetailsAllOfStatistics';
export * from './getExtendedContactDetailsAllOfStatisticsClicked';
export * from './getExtendedContactDetailsAllOfStatisticsLinks';
export * from './getExtendedContactDetailsAllOfStatisticsMessagesSent';
export * from './getExtendedContactDetailsAllOfStatisticsOpened';
export * from './getExtendedContactDetailsAllOfStatisticsUnsubscriptions';
export * from './getExtendedContactDetailsAllOfStatisticsUnsubscriptionsAdminUnsubscription';
export * from './getExtendedContactDetailsAllOfStatisticsUnsubscriptionsUserUnsubscription';
export * from './getExtendedList';
export * from './getExtendedListAllOf';
export * from './getExtendedListAllOfCampaignStats';
export * from './getFolder';
export * from './getFolderLists';
export * from './getFolders';
export * from './getIp';
export * from './getIpFromSender';
export * from './getIps';
export * from './getIpsFromSender';
export * from './getList';
export * from './getLists';
export * from './getProcess';
export * from './getProcesses';
export * from './getReports';
export * from './getReportsReports';
export * from './getSendersList';
export * from './getSendersListIps';
export * from './getSendersListSenders';
export * from './getSharedTemplateUrl';
export * from './getSmsCampaign';
export * from './getSmsCampaignAllOf';
export * from './getSmsCampaignOverview';
export * from './getSmsCampaignStats';
export * from './getSmsCampaigns';
export * from './getSmsEventReport';
export * from './getSmsEventReportEvents';
export * from './getSmtpTemplateOverview';
export * from './getSmtpTemplateOverviewSender';
export * from './getSmtpTemplates';
export * from './getSsoToken';
export * from './getStatsByDevice';
export * from './getTransacAggregatedSmsReport';
export * from './getTransacBlockedContacts';
export * from './getTransacBlockedContactsContacts';
export * from './getTransacBlockedContactsReason';
export * from './getTransacEmailContent';
export * from './getTransacEmailContentEvents';
export * from './getTransacEmailsList';
export * from './getTransacEmailsListTransactionalEmails';
export * from './getTransacSmsReport';
export * from './getTransacSmsReportReports';
export * from './getWebhook';
export * from './getWebhooks';
export * from './manageIp';
export * from './postContactInfo';
export * from './postContactInfoContacts';
export * from './postSendFailed';
export * from './postSendSmsTestFailed';
export * from './remainingCreditModel';
export * from './remainingCreditModelChild';
export * from './remainingCreditModelReseller';
export * from './removeContactFromList';
export * from './removeCredits';
export * from './requestContactExport';
export * from './requestContactExportCustomContactFilter';
export * from './requestContactImport';
export * from './requestContactImportNewList';
export * from './requestSmsRecipientExport';
export * from './sendEmail';
export * from './sendEmailAttachment';
export * from './sendReport';
export * from './sendReportEmail';
export * from './sendSms';
export * from './sendSmtpEmail';
export * from './sendSmtpEmailAttachment';
export * from './sendSmtpEmailBcc';
export * from './sendSmtpEmailCc';
export * from './sendSmtpEmailMessageVersions';
export * from './sendSmtpEmailReplyTo';
export * from './sendSmtpEmailReplyTo1';
export * from './sendSmtpEmailSender';
export * from './sendSmtpEmailTo';
export * from './sendSmtpEmailTo1';
export * from './sendTemplateEmail';
export * from './sendTestEmail';
export * from './sendTestSms';
export * from './sendTransacSms';
export * from './updateAttribute';
export * from './updateAttributeEnumeration';
export * from './updateCampaignStatus';
export * from './updateChild';
export * from './updateChildAccountStatus';
export * from './updateChildDomain';
export * from './updateContact';
export * from './updateEmailCampaign';
export * from './updateEmailCampaignRecipients';
export * from './updateEmailCampaignSender';
export * from './updateList';
export * from './updateSender';
export * from './updateSmsCampaign';
export * from './updateSmtpTemplate';
export * from './updateSmtpTemplateSender';
export * from './updateWebhook';
export * from './uploadImageToGallery';
import localVarRequest = require('request');
export declare class ObjectSerializer {
    static findCorrectType(data: any, expectedType: string): any;
    static serialize(data: any, type: string): any;
    static deserialize(data: any, type: string): any;
}
export interface Authentication {
    applyToRequest(requestOptions: localVarRequest.Options): Promise<void> | void;
}
export declare class HttpBasicAuth implements Authentication {
    username: string;
    password: string;
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class HttpBearerAuth implements Authentication {
    accessToken: string | (() => string);
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class ApiKeyAuth implements Authentication {
    private location;
    private paramName;
    apiKey: string;
    constructor(location: string, paramName: string);
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class OAuth implements Authentication {
    accessToken: string;
    applyToRequest(requestOptions: localVarRequest.Options): void;
}
export declare class VoidAuth implements Authentication {
    username: string;
    password: string;
    applyToRequest(_: localVarRequest.Options): void;
}
export declare type Interceptor = (requestOptions: localVarRequest.Options) => (Promise<void> | void);
